### ISSUE TITLE
Small issue with cantilever formulations

### ISSUE THREAD

**Issue by Agent6-6-6** [Agent6-6-6/Beam-Formulae-functions#1]
The rotational components for deflections should not be within an enclosing TAN() function.

Noted very small differences previously that were put down to numerical precision issues when verifying results. But checking larger deflection scenarios highlighted a divergence from verification cases.

Remove enclosing TAN() functions to resolve.

**Comment by buddyd16** [comment]
technically the TAN( theta) would actually be appropriate but we are always taught to use small angle approximation since TAN(theta) approaches theta, as long as theta is in radians, at the angles we are typically dealing with for the cross section rotations it's pretty common place at this point to just do theta * the cantilever leg for the additional deflection. There might be some extra binary math error down at these low values with the transcendental functions also, looks like at an angle of 2E-6 radians doing the asin(acos(atan(tan(cos(sin(theta)))) check Excel loses precision and returns 1.99998E-6 instead of 2E-6.

https://en.wikipedia.org/wiki/Small-angle_approximation

If you want a back check on any of your formulas I dumped my derivations to the open-struct-engineer group in the general analysis excel folder, should be the only .bas files in there.

**Comment by Agent6-6-6** [comment]
The issue was at larger rotations TAN(theta) != theta. I was finding compared to my verification in SpaceGass that for larger rotations (and hence deflections) I was out by up to 5% higher. By larger deflections in the cases I was looking at anything creeping up near what you might practically assume is beyond any acceptable limit for a simply supported beam, but for seismic loading you can approach these larger deflections where the difference seems to matter/affect results. 

I simply took the approach of matching the analysis package I use. But you've got me thinking now I might have been right all along (I wrote these functions years ago, and only just got round to putting them in a format that others can utilise, so looking back on it I have no idea what I did!).

For small deflections/rotations that you might see in a well proportioned beam (sort of span/300 territory), it barely made a difference, maybe the second decimal place was out by 0.01.

**Comment by Agent6-6-6** [comment]
@buddyd16, by the way, just checked a few simple point load cases on a cantilever against your functions in the general_beam_analysis_MR.xlsm file you provided, and pretty much getting the same answer up to 2-3 decimal places when converted back to metric.
